# Generated by Django 5.0.1 on 2024-02-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingredients',
            new_name='materials',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='weight_grams',
            new_name='rarity',
        ),
    ]
